version: '3.8'
services:
  db:
    image: 'postgres:13.3-alpine3.14'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: fivetonine_development
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  