@host = http://localhost:3000

### create url
POST {{host}}/urls
Content-Type: application/json

{
  "source": "http://carloshdelreal.com" 
}

### get urls
GET {{host}}/urls

### show url
GET {{host}}/urls/1

### show url
GET {{host}}/b210d0d20d
